os: osx
osx_image: xcode9
xcode_project: Betacraft Launcher macoS.xcodeproj
xcode_scheme: Betacraft Launcher macoSTests
script:
- set -o pipefail
- xcodebuild build -workspace CalendarKitDemo.xcworkspace -scheme "CalendarKitDemo" -sdk iphonesimulator | xcpretty